pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    btshirt:
                        items: {  }
                        medias: {  }
                        name: btshirt
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697776231
                        creationDate: 1697776226
                        preserveAnimation: false
