pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    content:
                        items:
                            -
                                method: frame
                                arguments:
                                    width: 400
                                    height: 400
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#ff6600'
                            -
                                method: roundCorners
                                arguments:
                                    width: 10
                                    height: 10
                        medias: {  }
                        name: content
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697006561
                        creationDate: 1695811837
                        preserveAnimation: false
