pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    employee:
                        items: {  }
                        medias: {  }
                        name: employee
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1695965197
                        creationDate: 1695965173
                        preserveAnimation: false
