pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    logo:
                        items:
                            -
                                method: frame
                                arguments:
                                    width: 200
                                    height: 200
                                    forceResize: false
                            -
                                method: rotate
                                arguments:
                                    angle: 30
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#ff5733'
                            -
                                method: roundCorners
                                arguments:
                                    width: 10
                                    height: 10
                        medias: {  }
                        name: logo
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697008721
                        creationDate: 1697003729
                        preserveAnimation: false
