pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    salvar:
                        items: {  }
                        medias: {  }
                        name: salvar
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697777735
                        creationDate: 1697777732
                        preserveAnimation: false
