pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    wjeans:
                        items: {  }
                        medias: {  }
                        name: wjeans
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697706453
                        creationDate: 1697706446
                        preserveAnimation: false
